#!/bin/bash

/usr/bin/clear

BASHLIST=(
  yum
  cron
  apcupsd
  ipv4
  ipv6
  localize
  lm_sensors
  vim
  sudo
  service
  selinux
  munin
  postfix
  ssh
  minecraft
)

RUNLIST=()
cur=0
for curBash in ${BASHLIST[@]}
do
  while true
  do
    cur=$(expr $cur + 1)
    read -p "("$cur"/"${#BASHLIST[@]}") Do you want to run '"$curBash"' script? [Y/n](default:Y): " ans
    case $ans in
      '' | [Yy]* )
        RUNLIST+=("$curBash")
        break;
        ;;
      [Nn]* )
        break;
        ;;
      * )
        echo "Please answer Y or n."
    esac
  done
done

setup_apcupsd () {
  echo "Start setup apcupsd.";

  if [ ! -f /etc/apcupsd/apcupsd.conf.org ]
  then
    cp -p /etc/apcupsd/apcupsd.conf /etc/apcupsd/apcupsd.conf.org
  fi
  sed -i -e 's/TIMEOUT 0/TIMEOUT 60/g' /etc/apcupsd/apcupsd.conf

  while true
  do
    read -p "UPSサービスを有効にしますか? [Y/n](default:n): " ans
    case $ans in
      [Yy]* )
        systemctl enable apcupsd.service
        break;
        ;;
      '' | [Nn]* )
        break;
        ;;
      * )
        echo "Please answer Y or n."
    esac
  done
}

setup_cron () {
  echo "Start setup cron.";

  echo -n "cronエラーの通知先メアドを入力してください(default:admin@example.net): "
  read mail
  if [ -z "$mail" ]
  then
    mail="admin@example.net"
  fi

  cat << __EOS__ > /root/crontabs.org
MAILTO="$mail"
# Minute Hour Day Month Week command
0 0 * * * screen -p 0 -S minecraft -X eval 'stuff "say 先生。日跨いだお！ (￣◇￣;)ｴｯ"\015' 1> /dev/null
0 1 * * * screen -p 0 -S minecraft -X eval 'stuff "say 先生。そろそろ寝る時間ですよ(@￣ρ￣@)ｚｚｚｚ"\015' 1> /dev/null
0 2 * * * screen -p 0 -S minecraft -X eval 'stuff "say 先生。先に寝てます(´-ω-)｡o○"\015' 1> /dev/null
0 8 * * * screen -p 0 -S minecraft -X eval 'stuff "say 先生。おはよう～(´･ω･｀)"\015' 1> /dev/null
1 */3 * * * bash /opt/minecraft/shell/backup.sh 1> /dev/null
10 0 * * * bash /opt/minecraft/shell/clearlog.sh 1> /dev/null
20 5 1 * * bash /opt/minecraft/shell/reset-mining.sh 1> /dev/null
30 5 * * 1 bash /opt/minecraft/shell/reset-the-end.sh 1> /dev/null
__EOS__

  useradd minecraft
  echo ""
  echo ""
  echo "マインクラフトユーザーを作成しました。パスワードを設定してください。"
  passwd minecraft

  crontab -u minecraft /root/crontabs.org
  /bin/rm -f /root/crontabs.org
}

setup_ipv4 () {
  echo "Start setup ipv4.";

  if [ ! -f /etc/sysctl.conf.org ]
  then
    cp -p /etc/sysctl.conf /etc/sysctl.conf.org
  fi

  cat << '__EOS__' >> /etc/sysctl.conf
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 20
__EOS__
  sysctl -p
}

setup_ipv6 () {
  echo "Start setup ipv6.";

  # ip a
  echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.d/disable_ipv6.conf
  echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.d/disable_ipv6.conf
  sysctl -p /etc/sysctl.d/disable_ipv6.conf
  if [ ! -f /etc/sysctl.d/disable_ipv6.conf.org ]
  then
    cp -p /etc/sysctl.d/disable_ipv6.conf /etc/sysctl.d/disable_ipv6.conf.org
  fi
}

setup_lm_sensors () {
  echo "Start setup lm_sensors.";

  yes "" | sensors-detect
}

setup_localize () {
  echo "Start setup localize.";

  # localectl list-locales | grep -i ja
  localectl set-locale LANG=ja_JP.utf8

  # timedatectl list-timezones | grep Tokyo
  timedatectl set-timezone Asia/Tokyo

  # localectl list-keymaps | grep jp
  # localectl set-keymap jp106
  # localectl

}

setup_munin () {
  echo "Start setup munin.";

  cat << '__EOS__' > /etc/munin/plugins/minecraft
#!/bin/sh

MC_PORT=25565
RH_VERSION=$(cat /etc/redhat-release | grep -Eo '[0-9]+' | head -1)

if [ "$1" = "autoconf" ]
then
    printf "yes\n"
    exit 0
fi

if [ "$1" = "config" ]
then
    printf 'graph_title Minecraft server\n'
    printf 'graph_vlabel Number\n'
    printf 'graph_category Minecraft\n'
    printf 'users.label User\n'
    printf 'ramusage.label Used RAM in GiB\n'
    exit 0
fi

if [ $RH_VERSION -ge 7 ]
then
  PLAYERCOUNT=$(ss -tn | grep -i ${MC_PORT} | grep ESTAB | wc -l )
else
  PLAYERCOUNT=$(netstat -tn | grep -i ${MC_PORT} | grep ESTABLISHED | wc -l)
fi

MC_PID=$(ps -ef | grep 'spigot' | grep -v 'SCREEN' | grep -v 'grep' | awk '{print $2}')
if [ ! -z "${MC_PID}" ]
then #is running
    MEMORYRSS=$(ps -p ${MC_PID} -o rss | grep -v RSS)
    MEMGiB=$(echo "scale=2;${MEMORYRSS}/1024/1024" | bc -l)
else
    MEMGiB=0
fi

printf "users.value %i\n" "${PLAYERCOUNT}"
printf "ramusage.value %3.2f\n" "${MEMGiB}"
__EOS__
  chmod 755 /etc/munin/plugins/minecraft
  ln -s /usr/share/munin/plugins/sensors_ sensors_temp

  if [ ! -f ./apcupsd_ww ]
  then
    wget https://raw.githubusercontent.com/munin-monitoring/contrib/master/plugins/power/apcupsd_ww
  fi
  cp -p ./apcupsd_ww /etc/munin/plugins/apcupsd_ww
  chmod 755 /etc/munin/plugins/apcupsd_ww
  echo -n "muninでping監視したいゲートウェイアドレスを指定してください。(default:192.168.1.1): "
  read chkipaddr
  if [ -z "$chkipaddr" ]
  then
    chkipaddr="192.168.1.1"
  fi
  ln -s /usr/share/munin/plugins/ping_ /etc/munin/plugins/ping_$chkipaddr

  echo -n "muninでping監視したいドメインを指定してください。(default:example.net): "
  read $chkdomain
  if [ -z "$chkdomain" ]
  then
    chkdomain="example.net"
  fi
  ln -s /usr/share/munin/plugins/ping_ /etc/munin/plugins/ping_$chkdomain

  if [ ! -f  /etc/munin/munin-node.conf.org ]
  then
    cp -p  /etc/munin/munin-node.conf  /etc/munin/munin-node.conf.org
  fi
  sed -i -e 's/localhost.localdomain/'`hostname`'/g' /etc/munin/munin-node.conf

  echo -n "muninのサーバーアドレスを入力してください。(default:192.168.1.1): "
  read serveripaddr
  if [ -z "$serveripaddr" ]
  then
    serveripaddr="192.168.1.1"
  fi
  serveripaddr=${serveripaddr//./\\\\.}
  sed -i -e "/^allow \^::1\$$/a allow \^"$serveripaddr"\$" /etc/munin/munin-node.conf

  if [ ! -f /etc/munin/plugin-conf.d/munin-node.org ]
  then
    cp -p /etc/munin/plugin-conf.d/munin-node /etc/munin/plugin-conf.d/munin-node.org
  fi
  echo "" >> /etc/munin/plugin-conf.d/munin-node
  echo "[sensors_*]" >> /etc/munin/plugin-conf.d/munin-node
  echo "user root" >> /etc/munin/plugin-conf.d/munin-node

  cat << '__EOS__' > /etc/firewalld/services/munin-node.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>munin-node</short>
  <description>munin-node</description>
  <port protocol="tcp" port="4949"/>
</service>
__EOS__
  firewall-cmd --reload
  firewall-cmd --permanent --add-service=munin-node

  systemctl enable munin-node.service
}

setup_postfix () {
  echo "Start setup postfix.";

  if [ ! -f /etc/postfix/main.cf.org ]
  then
    cp -p /etc/postfix/main.cf /etc/postfix/main.cf.org
  fi

  cat << '__EOS__' > /etc/postfix/main.cf
queue_directory = /var/spool/postfix
command_directory = /usr/sbin
daemon_directory = /usr/libexec/postfix
data_directory = /var/lib/postfix
mail_owner = postfix
inet_interfaces = localhost
inet_protocols = ipv4
mydestination = $myhostname, localhost.$mydomain, localhost
unknown_local_recipient_reject_code = 550
relayhost = 192.168.1.1
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
debug_peer_level = 2
debugger_command =
	 PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
	 ddd $daemon_directory/$process_name $process_id & sleep 5
sendmail_path = /usr/sbin/sendmail.postfix
newaliases_path = /usr/bin/newaliases.postfix
mailq_path = /usr/bin/mailq.postfix
setgid_group = postdrop
html_directory = no
manpage_directory = /usr/share/man
sample_directory = /usr/share/doc/postfix-2.10.1/samples
readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
__EOS__

  echo -n "postfixが利用するrelayhostを入力してください。(default:192.168.1.1): "
  read serveripaddr
  if [ -z "$serveripaddr" ]
  then
    serveripaddr="192.168.1.1"
  fi
  sed -i -e "s/192.168.1.1/"$serveripaddr"/g" /etc/postfix/main.cf 

  systemctl enable postfix.service
  systemctl start postfix.service
  systemctl restart postfix.service
}

setup_selinux () {
  echo "Start setup selinux.";

  if [ ! -f /etc/selinux/config.org ]
  then 
    cp -p /etc/selinux/config /etc/selinux/config.org
  fi
  sed -i -e 's/=enforcing/=disabled/g' /etc/selinux/config
}

setup_service () {
  echo "Start setup service.";

  # systemctl list-units --type=service
  # systemctl list-unit-files | grep enabled
  systemctl disable auditd.service
  systemctl disable kdump.service
  systemctl disable chronyd.service
  systemctl disable wpa_supplicant
  systemctl disable NetworkManager

}

setup_ssh () {
  echo "Start setup ssh.";

  if [ ! -f ./id_rsa.pub ] \
    || [ ! -f ./id_rsa ]
  then
    mkdir -p ~/.ssh
    ssh-keygen -t rsa -b 4096      # Create key pair.RSA 4096bit
    cp -p ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
    cp -p ~/.ssh/id_rsa.pub ./id_rsa.pub
    cp -p ~/.ssh/id_rsa ./id_rsa
  else
    cp -p ./id_rsa.pub ~/.ssh/id_rsa.pub
    cp -p ./id_rsa ~/.ssh/id_rsa
  fi

  cat << '__EOS__' > ~/.ssh/config
Host host1.example.net
  HostName            192.168.1.1
  Port                22
  User                root
  IdentityFile        /home/dummy/.ssh/id_rsa_host1
  ServerAliveInterval 60
  UseRoaming no
Host host2.example.net
  HostName            192.168.1.2
  Port                22
  User                root
  IdentityFile        /home/dummy/.ssh/id_rsa_host1
  ServerAliveInterval 60
  UseRoaming no
Host host3.example.net
  HostName            192.168.1.3
  Port                22
  User                root
  IdentityFile        /home/dummy/.ssh/id_rsa_host1
  ServerAliveInterval 60
  UseRoaming no
__EOS__

  # firewall-cmd --state
  # firewall-cmd --list-all
  # firewall-cmd --list-all-zones
  # firewall-cmd --list-all --zone=public
  # ss -antup
  # ip addr
  cat << '__EOS__' > /etc/firewalld/services/ssh.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>SSH</short>
  <description>Secure Shell (SSH) is a protocol for logging into and executing commands on remote machines. It provides secure encrypted communications. If you plan on accessing your machine remotely via SSH over a firewalled interface, enable this option. You need the openssh-server package installed for this option to be useful.</description>
  <port protocol="tcp" port="22"/>
</service>
__EOS__

  echo -n "sshが利用するportを入力してください。(default:22): "
  read serverport
  if [ -z "$serverport" ]
  then
    serverport="22"
  fi
  sed -i -e "s/22/"$serverport"/g" ~/.ssh/config

  cp -p /etc/ssh/sshd_config /etc/ssh/sshd_config.org
  sed -i -e "s/#Port 22/Port "$serverport"/g" /etc/ssh/sshd_config

  echo -n "sshでrootログインを許可しますか?(本番運用時はrootログインを停止することを推奨します) [Y/n](default:Y): "
  read rootlogin
  if [ -z "$rootlogin" -o "$rootlogin" = "Y" -o "$rootlogin" = "y" ]
  then
    sed -i -e "s/#PermitRootLogin yes/PermitRootLogin yes/g" /etc/ssh/sshd_config
  else
    sed -i -e "s/#PermitRootLogin yes/PermitRootLogin no/g" /etc/ssh/sshd_config
  fi
  
  sed -i -e "s/#PubkeyAuthentication yes/PubkeyAuthentication yes/g" /etc/ssh/sshd_config
  sed -i -e "s/#PasswordAuthentication yes/PasswordAuthentication no/g" /etc/ssh/sshd_config
  sed -i -e "s/#PermitEmptyPasswords no/PermitEmptyPasswords no/g" /etc/ssh/sshd_config
  
  sed -i -e "s/22/"$serverport"/g" /etc/firewalld/services/ssh.xml

  firewall-cmd --reload
  firewall-cmd --permanent --add-service=ssh
  chmod 600 /root/.ssh
  chmod 600 -R /root/.ssh
  echo "*************** SSH PRIVATE KEY START ***************"
  echo " SSH接続する際に必要になりますので、下記は必ず控えを取ってください。"
  cat ~/.ssh/id_rsa
  echo " SSH接続する際に必要になりますので、上記は必ず控えを取ってください。"
  echo "*************** SSH PRIVATE KEY END ***************"
  read ans
  echo "画面をリフレッシュします。SSH PRIVATE KEYを保存している場合は、何かキーを押して続行してください。"
  read ans
}

setup_sudo () {
  echo "Start setup sudo.";

  if [ ! -f /etc/sudoers.org ]
  then
    cp -p /etc/sudoers /etc/sudoers.org
  fi
  echo "" >> /etc/sudoers
  echo "# add minecraft user systemctl" >> /etc/sudoers
  echo "Cmnd_Alias MINECRAFT_SERVICE = /bin/systemctl * minecraft.service" >> /etc/sudoers
  echo "minecraft    ALL=NOPASSWD: MINECRAFT_SERVICE" >> /etc/sudoers
  echo "" >> /etc/sudoers
}

setup_vim () {
  echo "Start setup vim.";

  cat << '__EOS__' > ~/.vimrc
:map mp :'s,'ey<LF>p
:set tabstop=4
:set noautoindent
:set expandtab
:set shiftwidth=4
__EOS__

  cat << '__EOS__' >> ~/.bashrc

alias vi='vim'
__EOS__
}

setup_yum () {
  echo "Start setup yum.";

  yum install --downloadonly --downloaddir=./ java-1.8.0-openjdk-devel
  yum -y install java-1.8.0-openjdk-devel

  yum install --downloadonly --downloaddir=./ unzip
  yum -y install unzip

  yum install --downloadonly --downloaddir=./ wget
  yum -y install wget

  yum install --downloadonly --downloaddir=./ bind-utils
  yum -y install bind-utils

  yum install --downloadonly --downloaddir=./ expect
  yum -y install expect

  yum install --downloadonly --downloaddir=./ bc
  yum -y install bc
    
  yum install --downloadonly --downloaddir=./ gcc
  yum -y install gcc

  yum install --downloadonly --downloaddir=./ gcc-c++
  yum -y install gcc-c++

  yum install --downloadonly --downloaddir=./ gdb
  yum -y install gdb

  yum install --downloadonly --downloaddir=./ lm_sensors
  yum -y install lm_sensors

  yum install --downloadonly --downloaddir=./ tcpdump
  yum -y install tcpdump

  yum install --downloadonly --downloaddir=./ telnet
  yum -y install telnet

  yum install --downloadonly --downloaddir=./ iotop
  yum -y install iotop
 
  yum install --downloadonly --downloaddir=./ GeoIP-data
  yum -y install GeoIP-data
 
  yum install --downloadonly --downloaddir=./ GeoIP-update
  yum -y install GeoIP-update

  yum install --downloadonly --downloaddir=./ git
  yum -y install git
  
  yum install --downloadonly --downloaddir=./ java-1.8.0-openjdk
  yum -y install java-1.8.0-openjdk

  yum install --downloadonly --downloaddir=./ screen
  yum -y install screen

  yum install --downloadonly --downloaddir=./ vim
  yum -y install vim

  wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  rpm -ivh ./epel-release-latest-7.noarch.rpm

  yum install --downloadonly --downloaddir=./ --enablerepo=epel apcupsd
  yum -y install --enablerepo=epel apcupsd

  yum install --downloadonly --downloaddir=./ --enablerepo=epel iftop  
  yum -y install --enablerepo=epel iftop

  yum install --downloadonly --downloaddir=./ --enablerepo=epel munin-node
  yum -y install --enablerepo=epel munin-node

  yum install --downloadonly --downloaddir=./ --enablerepo=epel nkf
  yum -y install --enablerepo=epel nkf
}

setup_minecraft () {
  echo "Start setup minecraft.";

  echo -n "ビルドするマインクラフトサーバーのバージョンを指定してください。(default:1.13.2): "
  read mcversion
  if [ -z "$mcversion" ]
  then
    mcversion="1.13.2"
  fi

  if [ ! -f ./BuildTools.jar ]
  then
    wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
  fi
  build_dir='/opt/build_minecraft/'`date +%Y%m%d`'/'
  mkdir -p $build_dir
  cp -p ./BuildTools.jar $build_dir
  cd $build_dir
  java -jar ./BuildTools.jar -rev $mcversion
  mkdir -p /opt/minecraft/
  cp ./spigot-*.jar /opt/minecraft/

  memTotal=`free -m | grep ^Mem | tr -s ' ' | cut -d ' ' -f 2`
  cat << __EOS__ > /opt/minecraft/environments
JAVA_OPTIONS='-Dfile.encoding=UTF-8 -Xms$(( $memTotal / 10 * 1))m -Xmx$(( $memTotal / 10 * 9))m -XX:+UseG1GC -XX:MaxGCPauseMillis=50'
JAR_SPIGOT='spigot-$mcversion.jar'
JAR_OPTIONS='nogui'
__EOS__

  cat << '__EOS__' > /etc/firewalld/services/minecraft.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Minecraft Server</short>
  <description>Minecraft Server</description>
  <port protocol="tcp" port="25565"/>
</service>
__EOS__
  cat << '__EOS__' > /etc/firewalld/services/minecraft-votifier.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Minecraft Votifier</short>
  <description>Minecraft Votifier</description>
  <port protocol="tcp" port="8192"/>
</service>
__EOS__
  cat << '__EOS__' > /etc/firewalld/services/minecraft-dynmap.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Minecraft Dynmap</short>
  <description>Minecraft Dynmap</description>
  <port protocol="tcp" port="8123"/>
</service>
__EOS__
  firewall-cmd --reload
  firewall-cmd --permanent --add-service=minecraft
  firewall-cmd --permanent --add-service=minecraft-votifier
  firewall-cmd --permanent --add-service=minecraft-dynmap

  cat << '__EOS__' > /etc/systemd/system/minecraft.service
[Unit]
Description=Minecraft Server
Requires=network.target local-fs.target
After=network.target local-fs.target

[Service]
RemainAfterExit=yes
Restart=always
User=minecraft
Group=minecraft
EnvironmentFile=/opt/minecraft/environments
WorkingDirectory=/opt/minecraft
ExecStart=/usr/bin/screen -AmdS minecraft /usr/bin/java $JAVA_OPTIONS -jar $JAR_SPIGOT $JAR_OPTIONS
ExecReload=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "say メンテナンスの為、5秒後に鯖をリロードします"\015'
ExecReload=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "say 一時的にラグが発生しますがご了承ください"\015'
ExecReload=/usr/bin/sleep 5
ExecReload=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "reload"\015'
ExecReload=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "say リロードが完了しました"\015'
ExecStop=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "say メンテナンスの為、5秒後に鯖を停止します"\015'
ExecStop=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "say 自動的に切断されますので、ご了承ください"\015'
ExecStop=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "save-all"\015'
ExecStop=/usr/bin/sleep 5
ExecStop=/usr/bin/screen -p 0 -S minecraft -X eval 'stuff "stop"\015'
ExecStop=/usr/bin/sleep 10
ExecStop=/usr/bin/sync

[Install]
WantedBy=multi-user.target
__EOS__

  systemctl daemon-reload
  systemctl enable minecraft.service
  # echo "Detaching From Screen: Ctrl + A + D"
  # su - minecraft -c "screen -R minecraft"

  mkdir -p /opt/minecraft/shell/
  cat << '__EOS__' > /opt/minecraft/shell/clearlog.sh
#!/bin/bash

find /opt/minecraft/logs/*.log.gz -mtime +31 | xargs /bin/rm -f
screen -p 0 -S minecraft -X eval 'stuff "co purge t:30d"\015'

__EOS__

  cat << '__EOS__' > /opt/minecraft/shell/reset-mining.sh
#!/bin/bash

screen -p 0 -S minecraft -X eval 'stuff "say 5分後に全資源ワールドの初期化を開始します"\015'
screen -p 0 -S minecraft -X eval 'stuff "say 資源ワールドにいる方はワールド外へ退避してください"\015'
sleep 300

screen -p 0 -S minecraft -X eval 'stuff "say 資源ワールド(NORMAL)の初期化を開始します"\015'
screen -p 0 -S minecraft -X eval 'stuff "mv regen world_mining -S"\015'
screen -p 0 -S minecraft -X eval 'stuff "mvconfirm"\015'
sleep 30

screen -p 0 -S minecraft -X eval 'stuff "say 資源ワールド(NETHER)の初期化を開始します"\015'
screen -p 0 -S minecraft -X eval 'stuff "mv regen world_mining_nether -S"\015'
screen -p 0 -S minecraft -X eval 'stuff "mvconfirm"\015'
sleep 30

screen -p 0 -S minecraft -X eval 'stuff "say 再読み込みをします"\015'
screen -p 0 -S minecraft -X eval 'stuff "reload"\015'
sleep 30

screen -p 0 -S minecraft -X eval 'stuff "say 資源ワールドの初期化を完了しました"\015'
screen -p 0 -S minecraft -X eval 'stuff "dynmap fullrender world_mining"\015'
screen -p 0 -S minecraft -X eval 'stuff "dynmap fullrender world_mining_nether"\015'

__EOS__

  cat << '__EOS__' > /opt/minecraft/shell/reset-the-end.sh
#!/bin/bash

screen -p 0 -S minecraft -X eval 'stuff "say $(( $RESET_WAIT / 60 ))分後にジ・エンドの初期化を開始します"\015'
screen -p 0 -S minecraft -X eval 'stuff "say サービスを再起動する為、ログアウトをお願いします"\015'

sudo systemctl stop minecraft.service

sleep 30
/bin/rm -rf /opt/minecraft/world_the_end

sudo systemctl start minecraft.service

screen -p 0 -S minecraft -X eval 'stuff "dynmap fullrender world_the_end"\015'

__EOS__

  cat << '__EOS__' > /opt/minecraft/shell/backup.sh
#!/bin/bash

screen -p 0 -S minecraft -X eval 'stuff "say バックアップを開始します"\015'
screen -p 0 -S minecraft -X eval 'stuff "save-off"\015'
screen -p 0 -S minecraft -X eval 'stuff "save-all"\015'
sync
rsync -aurv --delete --exclude /opt/minecraft/plugins/CoreProtect/database.db /opt/minecraft /backup/history/`date +'%H'`/
screen -p 0 -S minecraft -X eval 'stuff "save-on"\015'
screen -p 0 -S minecraft -X eval 'stuff "say バックアップが完了しました"\015'

__EOS__

  chown minecraft:minecraft -R /opt/minecraft
  for i in {0..23}; do
    mkdir -p /backup/history/$(printf "%02d\n" $i)/
  done
  chown minecraft:minecraft -R /backup

}

for curBash in ${RUNLIST[@]}
do

    /usr/bin/clear

    case "$curBash" in
      apcupsd )
        setup_apcupsd
        ;;
      cron )
        setup_cron
        ;;
      ipv4 )
        setup_ipv4
        ;;
      ipv6 )
        setup_ipv6
        ;;
      lm_sensors )
        setup_lm_sensors
        ;;
      localize )
        setup_localize
        ;;
      munin )
        setup_munin
        ;;
      minecraft )
        setup_minecraft
        ;;
      postfix )
        setup_postfix
        ;;
      selinux )
        setup_selinux
        ;;
      service )
        setup_service
        ;;
      ssh )
        setup_ssh
        ;;
      sudo )
        setup_sudo
        ;;
      vim )
        setup_vim
        ;;
      yum )
        setup_yum
        ;;
      * )
        echo "ERROR:"$curBash
    esac
done

/usr/bin/clear
echo "reboot & systemctl start minecraft"
echo "Edit and Agree /opt/minecraft/eula.txt"
echo "Finished."
